# Generated by Django 2.0 on 2019-03-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20190317_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='comments',
            field=models.CharField(default='', max_length=200, verbose_name='评论'),
        ),
    ]
