# Generated by Django 2.0 on 2019-03-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_coursecomments_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '讲师'), (3, '学院机构')], default=1, verbose_name='收藏类型'),
        ),
    ]
