# Generated by Django 2.0 on 2019-03-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190325_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', upload_to='courses/lecturer_upload/%Y/%m', verbose_name='教师上传视频'),
        ),
    ]
