# Generated by Django 2.0 on 2019-03-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_lecturer',
            field=models.BooleanField(default=False, verbose_name='是否为教师'),
        ),
    ]
