# Generated by Django 2.0 on 2019-03-31 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_is_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_lecturer',
        ),
    ]
