# Generated by Django 2.0 on 2019-03-31 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_auto_20190331_2142'),
        ('users', '0003_remove_userprofile_is_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.Teacher', verbose_name='关联教师'),
        ),
    ]
