# Generated by Django 2.0 on 2019-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeorg',
            name='image',
            field=models.ImageField(upload_to='college_org/%Y/%m', verbose_name='学院logo'),
        ),
    ]
