# Generated by Django 2.0 on 2019-03-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_remove_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeorg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='college_org/%Y/%m', verbose_name='学院logo'),
        ),
    ]
